# Build settings

port: 4000
markdown:  kramdown
# url                      : /https://tomgor88.github.io/ # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io"
# baseurl                  : "www.thompsonwong.com/" # the subpath of your site, e.g. "/blog"
# repository               : "TomGor88/TestWeb.github.io"
# permalink: /:title
url            : "/https://www.thompsonwong.com/"
baseurl        : ""
repository     : "TomGor88/TestWeb.github.io"
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Thompson Wong's Portfolio"
description: "Powered by Jekyll and GitHub Pages"
author:      "Paul Le"
