#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
# - {name: 'Resume',     url: 'resume'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'UCSD Fomula FAE TritonRacing',   url: 'proj-1'}
- {name: 'Chess Robot UR10 Cobot',   url: 'proj-2'}
- {name: 'Robotic Puppy', url: 'proj-3'}
- {name: 'A.I. Robotic Arm',  url: 'proj-4'}
- {name: 'FIRST Gunn Robotics Team',  url: 'proj-5'}
- {name: 'RC Plane (UAV)',  url: 'proj-6'}

#-------------------------------
# Contact Section

social:
# - {icon: 'twitter',   link: 'https://twitter.com/paululele'}
# - {icon: 'file-text', link: "{{ site.github.url }}/assets/img/other/Thompson_Wong_Resume.pdf"}
- {icon: 'file-text', link: 'https://thompsonwong.com/resume'}
- {icon: 'instagram', link: 'https://instagram.com/t.wong__'}
- {icon: 'github',    link: 'https://github.com/TomGor88'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/twong124244'}
- {icon: 'envelope',  link: 'mailto:tcw003@ucsd.edu'}
# - {icon: 'file-text',   link: https://instagram.com/t.wong__'}
# - {icon: 'file-pdf',   link: https://instagram.com/t.wong__'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
